/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ChronoColis;

import org.junit.jupiter.api.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
      
    }
}
