/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chronoColis;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ChronColisApp  {
   public static void main(String[] args) {
     SpringApplication.run(ChronColisApp.class,args);
  }
}
